# permissions for end users to view formations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: formation-viewer-role
rules:
- apiGroups:
  - apps.poconetes.dev
  resources:
  - formations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.poconetes.dev
  resources:
  - formations/status
  verbs:
  - get
