# permissions for end users to edit formations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: formation-editor-role
rules:
- apiGroups:
  - apps.poconetes.dev
  resources:
  - formations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.poconetes.dev
  resources:
  - formations/status
  verbs:
  - get
