apiVersion: apps.poconetes.dev/v1
kind: Formation
metadata:
  name: autoscaling
  namespace: sample-project
  annotations:
    poco-build-stream: builder-sample
spec:
  minReplicas: 1
  maxReplicas: 10
  image: polinux/stress
  tls:
    issuer:
      kind: ClusterIssuer
      name: poconetes-internal 
    names:
    - autoscaling
    - autoscaling.default
  scaling:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
