apiVersion: apps.poconetes.dev/v1
kind: Formation
metadata:
  name: autoscaling
spec:
  minReplicas: 1
  maxReplicas: 10
  image: polinux/stress
  command: ["stress"]
  args: ["--vm", "1", "--vm-bytes", "700M", "--vm-hang", "1"]
  tls:
    issuer:
      kind: ClusterIssuer
      name: poconetes-internal 
    names:
    - autoscaling
    - autoscaling.default
  scaling:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
