# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/tunnels.poconetes.dev_clients.yaml
- bases/apps.poconetes.dev_formations.yaml
- bases/apps.poconetes.dev_plans.yaml
- bases/apps.poconetes.dev_sidecars.yaml
- bases/apps.poconetes.dev_initializers.yaml
- bases/apps.poconetes.dev_builds.yaml
- bases/apps.poconetes.dev_builders.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- patches/webhook_in_clients.yaml
- patches/webhook_in_formations.yaml
- patches/webhook_in_plans.yaml
- patches/webhook_in_sidecars.yaml
- patches/webhook_in_initializers.yaml
- patches/webhook_in_builds.yaml
- patches/webhook_in_builders.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- patches/cainjection_in_clients.yaml
- patches/cainjection_in_formations.yaml
- patches/cainjection_in_plans.yaml
- patches/cainjection_in_sidecars.yaml
- patches/cainjection_in_builds.yaml
- patches/cainjection_in_builders.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
