apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: project-ca
  namespace: cert-manager
spec:
  secretName: project-ca
  duration: 8736h # 1 year
  renewBefore: 240h # 10 days
  issuerRef:
    name: poconetes-internal
    kind: ClusterIssuer
  commonName: project-ca
  usages:
  - cert sign
  isCA: true
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: project-ca
spec:
  ca:
    secretName: project-ca
